[package]
name = "cargo-apk"
version = "0.1.0"
authors = ["Thomas Schaller (torkleyy)"]

[dependencies]
ansi_term = "0.9"
cargo-apk-lib = { path = "src/lib", version = "0.1.0" }
clap = "2"

[workspace]
members = ["src/lib"]
